### ISSUE TITLE
uh oh Something broke :(

### ISSUE THREAD

**Issue by apedance** [qJake/HADotNet.CommandCenter#20]
On every tile I want to add I get this error message.
How can I provide more insight?

**Comment by qJake** [comment]
Can you check the logs/output of the app (via the console / Docker container output) to see if there are any errors there?

It sounds like you don't have your HA base URL or access token set up quite right, or HACC is not able to reach your HA instance via HTTP/S, so check your container network settings as well.

**Comment by rbflurry** [comment]
I am seeing this as well.   I hope the below is helpful

`
      Initializing HA Client Factory with URL http://192.168.47.203 and access token [eyJ0eX•••••••••••mZCHJM].


fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]


      An unhandled exception has occurred while executing the request.


System.Exception: Unexpected response code 0 from Home Assistant API endpoint /api/states.


   at HADotNet.Core.BaseClient.Get[T](String path)


   at HADotNet.Core.Clients.EntityClient.GetEntities()


   at HADotNet.CommandCenter.Controllers.StateTileController.Add() in /src/HADotNet.CommandCenter-0.4.1/HADotNet.CommandCenter/Controllers/StateTileController.cs:line 26


   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)


   at System.Threading.Tasks.ValueTask`1.get_Result()


   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()


   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()


   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)


   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)


   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()


   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()


   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)


   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)


   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()


   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()


   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)


   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)


   at HADotNet.CommandCenter.Middleware.HAClientInitialization.InvokeAsync(HttpContext context) in /src/HADotNet.CommandCenter-0.4.1/HADotNet.CommandCenter/Middleware/HAClientInitialization.cs:line 48


   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)`

**Comment by qJake** [comment]
Yep - response code 0 indicates a network failure. Your address `http://192.168.47.203` is not accessible from within the HACC container.

Are you missing a port perhaps? (HA runs on 8123 by default...) Or if you're running HACC and HA in separate containers, I think some network bridging is required, but I'm not sure exactly what you'd need to do to fix it.

**Comment by azriele** [comment]
I am seeing this as well :(

**Comment by qJake** [comment]
@apedance @rbflurry @azriele Can you update to 0.5.0 and go to the "Settings" tab, and make sure communication with your HA instance is working? If not, check the container (console) logs for more information.
