### ISSUE TITLE
401 error when restarting HACC

### ISSUE THREAD

**Issue by BertrumUK** [qJake/HADotNet.CommandCenter#27]
Installed the new 0.5.0 version of HACC and added a device tracker as a test. This was working as expected. I stopped and restarted HACC and now I get the following error in the logs and the Web UI opens but does not fully populate the device tracker that I added

info: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Auto-initializing HACC via Hass.io addon.
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'RequestTileState'.
System.Exception: Unexpected response code 401 from Home Assistant API endpoint /api/states/device_tracker.neil.
   at HADotNet.Core.BaseClient.Get[T](String path)
   at HADotNet.Core.Clients.StatesClient.GetState(String entityId)
   at HADotNet.CommandCenter.Hubs.TileHub.RequestTileState(String tileName) in W:\GitHub\HADotNet.CommandCenter\HADotNet.CommandCenter\Hubs\TileHub.cs:line 50
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()

**Comment by qJake** [comment]
@BertrumUK I thought I could cache the auth token the system provides but I guess it's different for each start/stop of the container.

I'm about to push out 0.5.1 that fixes this since it's a breaking change. Give it about an hour and you should see the update for the addon.

**Comment by BertrumUK** [comment]
Just updated and its working again now. Thanks. Closing.
