### ISSUE TITLE
Covers/curtains

### ISSUE THREAD

**Issue by Keplernl** [qJake/HADotNet.CommandCenter#38]
## Describe the new functionality
Add the cover buttons, three buttons in 1 card: Up, stop and down

## What will it look like in the Admin area?
As an extra tile, but specially for covers (since these feature three buttons)

## What will it look like on the dashboard?
Something like this perhaps?
https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/8/0/804e56422f6250e0bb47b3688870125dafc6ce98.png

But maybe a better implementation can be used

## How will it work for standalone users vs. Hass.io Addon users?
?

**Comment by qJake** [comment]
@Keplernl Today, you can use a `cover` with a Switch tile, however you only get open/close functionality (like a garage door). I will leave this enhancement open to support a proper `cover` tile that also includes a stop button (optionally). 🙂

**Comment by Keplernl** [comment]
Ok, no problem that will do for now! Thanks

**Comment by arfrater** [comment]
I have added a cover (Garage Door) and pressing button nothing works
My Error is
`fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'OnTileClicked'.
HADotNet.Core.Domain.HttpResponseException: Exception of type 'HADotNet.Core.Domain.HttpResponseException' was thrown.
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String domain, String service, Object fields)
   at HADotNet.CommandCenter.Models.Config.Tiles.SwitchTile.OnClick(ServiceClient serviceClient) in /src/HADotNet.CommandCenter/Models/Config/Tiles/SwitchTile.cs:line 64
   at HADotNet.CommandCenter.Hubs.TileHub.OnTileClicked(String page, String tileName) in /src/HADotNet.CommandCenter/Hubs/TileHub.cs:line 54
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()
`
any idea @qJake
