### ISSUE TITLE
Grouped Light Bulbs not working via Switch Tile

### ISSUE THREAD

**Issue by fewyn** [qJake/HADotNet.CommandCenter#67]
## Description

I created a group of lights in my configuration then created a switch tile to control the multiple lights and when you click the tile it throws an API error and does nothing.

## Environment

<What version of HACC are you running?>
0.6.0

<What environment is it? Hass.io on a Raspberry Pi 3B+? AMD64 Docker on Alpine 3.10?>
Docker via Supervisor on Ubuntu 18.04

## Steps to Reproduce

1. Create Group of Lights
2. Create Switch tile in HACC
3. Click tile

## Screenshots

```
System.Exception: Unexpected response code 400 from Home Assistant API endpoint /api/services/switch/turn_on.
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String domain, String service, Object fields)
   at HADotNet.CommandCenter.Models.Config.Tiles.SwitchTile.OnClick(ServiceClient serviceClient) in /src/HADotNet.CommandCenter/Models/Config/Tiles/SwitchTile.cs:line 57
   at HADotNet.CommandCenter.Hubs.TileHub.OnTileClicked(String tileName) in /src/HADotNet.CommandCenter/Hubs/TileHub.cs:line 91
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()
```

**Comment by qJake** [comment]
Thanks for reporting this - will be released with version 1.0.
