### ISSUE TITLE
Cannot load web interface

### ISSUE THREAD

**Issue by avishayil** [qJake/HADotNet.CommandCenter#82]
## Description

After initializing hacc from the arm32v7 docker container, i'm receiving an error from ASP.NET

## Environment

arm32v7 docker container

RasberryPI 3B

## Steps to Reproduce

1. Pulled the container
2. Run the container
3. Try to access ip:8095

## Screenshots

````
[40m[32minfo[39m[22m[49m: HADotNet.CommandCenter.Startup[0]
      
        _    _          _____ _____ 
       | |  | |   /\   / ____/ ____|
       | |__| |  /  \ | |   | |     
       |  __  | / /\ \| |   | |     
       | |  | |/ ____ \ |___| |____ 
       |_|  |_/_/    \_\_____\_____|
              
       Home Assistant Command Center
              Version 1.0.12
      
      Now listening on: http://*:8095
      
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HADotNet.CommandCenter.Middleware.HAClientInitialization.InvokeAsync(HttpContext context) in W:\GitHub\HADotNet.CommandCenter\HADotNet.CommandCenter\Middleware\HAClientInitialization.cs:line 103
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
      An exception was thrown attempting to execute the error handler.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HADotNet.CommandCenter.Middleware.HAClientInitialization.InvokeAsync(HttpContext context) in W:\GitHub\HADotNet.CommandCenter\HADotNet.CommandCenter\Middleware\HAClientInitialization.cs:line 103
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUKMHV7IJQI", Request id "0HLUKMHV7IJQI:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HADotNet.CommandCenter.Middleware.HAClientInitialization.InvokeAsync(HttpContext context) in W:\GitHub\HADotNet.CommandCenter\HADotNet.CommandCenter\Middleware\HAClientInitialization.cs:line 103
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
````

**Comment by qJake** [comment]
Hey @avishayil I pushed out preview build 1.0.16 and updated the containers, can you let me know if this is fixed for you? Thanks!

**Comment by avishayil** [comment]
Seems that that specific bug is solved, thanks @qJake 
Could you elaborate what you did to solve it?

**Comment by qJake** [comment]
@avishayil The 1.0.x builds are all previews but I have to push them to Docker to test them in the HA Supervisor. So if you update Docker regularly, you'll have gotten a preview build.

Sorry for the inconvenience!
